### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [yibuyisheng/FE-knowledge#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by yibuyisheng** [comment]
This project is targeting to collect knowledges about front-end development. It is public and does not need any license.
